### ISSUE TITLE
This Is amazing ! Update question?

### ISSUE THREAD

**Issue by LePetitNewbie** [dylanwebbc/GolfPredictionModel#1]
Hi Dylan

This is another cracking project. Just confirming everything works well. Like with the Tennis, my question is regarding the process of updating the stats. I did clone the project when you release it for the Valspar Championship. The next Tournament was the Wells Fargo (ID 480). I entered "480" in the tournament.csv and ran the golfhandler.py as well as the golfpredictmodel.py. I followed the instructions to get the field for the Wells Fargo. I run it in the predictmodel.py and it works well. I did notice the golf.csv remaining the same as well as the golf_train.csv (Should these 2 files update with the past tournament stats which in this case would have been the Valspar Championship?)

Anyways, sorry about taking a bit of your time. 

Take Care
Ol

**Comment by dylanwebbc** [comment]
Hi Ol,

You don't need to modify the tournaments.csv file--if you run predictionModel("WellsFargo.csv", 2021, "480") the program will automatically add 480 to the tournaments.csv file if it isn't already there, and then scrape the data from the previous tournament. If 480 is already there, it will assume the data has been updated; you can use the files I've attached.

[golf_tournaments.csv](https://github.com/dylanwebbc/GolfPredictionModel/files/6550451/golf_tournaments.csv)
[WellsFargo.csv](https://github.com/dylanwebbc/GolfPredictionModel/files/6550452/WellsFargo.csv)

Hope this makes sense! Let me know if you have any further questions :)

-Dylan

**Comment by LePetitNewbie** [comment]
Hi Dylan
         Thanks very much for your reply. I followed your instructions and it worked perfectly. Really appreciate you taking the time to provide the right advice. Excellent work. 

Cheers
Ol
